#!/bin/sh
#
# chkconfig: 2345 98 02
# description: ASL is a fully extensible client-server suite that performs \
#   the real-time collection of system information, statistics, and log data. \
#   This information is collected centrally and archived into a database (or an \
#   RRD (http://people.ee.ethz.ch/~oetiker/webtools/rrdtool/) in the case of \
#   statistical data), and becomes the backend for many of the tools found in Spork
            
case "$1" in
  start)
	# Start daemon.
	echo "Starting asl"
        /opt/local/ASL/aslw.pl --nosyslog 1>/dev/null
	;;
  stop)
	# Stop daemon.
	echo "Shutting down asl"

        awkfield2='$1'
        pid=`ps -e | awk "/(_asls.pl|aslc.pl)/ && ! /awk/ { print $awkfield2; }"`
        [ "$pid" != "" ] && kill -KILL $pid

	;;
  restart|reload)
	$0 stop
	$0 start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	;;
esac

exit 0
